FROM keycloak/keycloak:24.0.0

# Configurar variables de entorno para UTF-8
ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
ENV LC_ALL=C.UTF-8

# Copiar temas personalizados
#COPY themes/zabud /opt/keycloak/themes/zabud

# Configuración de Java
#ENV JAVA_OPTS_APPEND="-Dkeycloak.profile.feature.upload_scripts=enabled"