version: '3.8'
services: 
  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile
    command: start --optimized
    environment:
      KC_HOSTNAME: keycloak.dobandov.com
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      # Configuración de BD simplificada para Keycloak 24
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db1:5432/keycloak-24
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: sfuKTJGExBqRTpPJXubX
      # Admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
    restart: unless-stopped
    ports:
      - 7029:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 20s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true